title: Hello, world! I'm David Freeman
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/lebmur" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Irene Lebrusan Murillo, Ph.D. # add your name
author-img: ire-face.jpg # add your photo
about-author: I am an <b>Urban Sociologist</b> <br>RCC Postdoctoral Researcher at <b>Harvard University</b>. #My main lines of research orbit around housing, inequality, old age, childhood and welfare system.
social-twitter: irenelebrusan
social-facebook: irene.lem.14
#social-github: artemsheludko # add your Github handle
social-linkedin: irene-lebrusán-murillo
social-email: ilebrusan@law.harvard.edu

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
